site_name: CiviCRM Documentation

nav:
  - Home:
    - Welcome: index.md
    - français: fr.md
    - Español: es.md
  - User Guide:
    - What is CiviCRM?: guides/user-guide/index.md
    - Organizing your data:
      - Topic 1: guides/user-guide/organizing-your-data/topic1.md
      - Topic 2: guides/user-guide/organizing-your-data/topic2.md
      - Topic 3: guides/user-guide/organizing-your-data/topic3.md
    - Searching and reporting: guides/user-guide/searching-and-reporting/index.md
    - Communication and messaging: guides/user-guide/communication-and-messaging/index.md
    - Events:
        - Introduction: guides/user-guide/events/index.md
        - Planning:
          - Creating an event: guides/user-guide/events/create.md
          - Settings: guides/user-guide/events/settings.md
          - Location: guides/user-guide/events/location.md
          - Setting Up Fees and Online Registration: guides/user-guide/events/fees.md
          - Reminders: guides/user-guide/events/reminders.md
        - Reporting: guides/user-guide/events/reporting.md
    - Membership: guides/user-guide/membership/index.md
    - Contributions:
        - Topic 1: guides/user-guide/contributions/topic1.md
        - Topic 2: guides/user-guide/contributions/topic2.md
        - Topic 3: guides/user-guide/contributions/topic3.md
    - Case Management: guides/user-guide/case-management/index.md
    - Advanced Topics: guides/user-guide/advanced-topics/index.md
  - Administator Guide:
    - Introduction: guides/admin-guide/index.md
  - Developer Guide:
    - Introduction: guides/developer-guide/index.md
  - Extensions:
    - Introduction: guides/extensions/index.md
  - About:
    - Introduction: guides/documentation-guide/index.md
    - Get Involved: guides/documentation-guide/get-involved.md
    - Style Guide: guides/documentation-guide/style.md

theme:
  name: material
  features:
    - navigation.tabs # This enables the top-level tabs
    # - navigation.instant # Optional: For instant page loading
    # - navigation.sections # Optional: If you want sections to collapse/expand

plugins:
  - search
  - tags
  - categories
